const data = [
    {
        title: 'Maldives',
        id: 0,
        image: require('./images/img3.jpg'),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?'
    },
    {
        title: 'Holi',
        id: 1,
        image: require('./images/img1.jpg'),
        text: 'Quisque pharetra ipsum vel urna fermentum fringilla. Quisque et nulla eleifend, porta eros in, faucibus tellus. Maecenas in leo posuere, commodo lectus in, dignissim risus. Duis imperdiet pharetra consequat. Aenean cursus lacinia ipsum, sollicitudin tincidunt lacus facilisis id. Nulla imperdiet massa turpis, sit amet mattis libero maximus vel. Vestibulum eget ligula vel dolor laoreet aliquet vel a tellus. Donec ultricies lacus quis felis egestas placerat. Fusce iaculis id lacus eu pulvinar. Nullam fermentum magna velit, non euismod odio vestibulum vel. Phasellus egestas nisi ut consectetur luctus. Suspendisse sagittis quam in sapien aliquet, quis pellentesque massa ornare. Sed non sagittis nisi, sed fermentum ex. Sed leo justo, pharetra ut pulvinar eget, efficitur a urna Quisque dapibus pretium dui, sit amet congue lacus venenatis non. Aliquam semper dolor sit amet ligula interdum, sed accumsan nunc tempus. Quisque tempor ex lacus, non consectetur tellus pharetra vel. Quisque pretium porta nibh, vel aliquam tortor iaculis ac. Mauris pulvinar nulla eget libero aliquam consequat. Pellentesque eu imperdiet orci. Mauris tincidunt feugiat dapibus. Sed sit amet purus a mi laoreet elementum.',
    },
    {
        title: 'Kashmir',
        id: 2,
        image: require('./images/img2.jpg'),
        text: 'Curabitur ullamcorper magna dui, quis mattis ante accumsan vitae. Suspendisse est sem, viverra quis ante id, vulputate cursus est. Donec aliquet eget felis blandit porta. Duis finibus porttitor lacinia. Quisque euismod egestas velit, vitae convallis ante maximus id. Fusce eget vestibulum turpis. Donec nec neque facilisis, egestas augue vel, mattis ligula. Morbi vitae lectus sem. Nullam porta, libero at condimentum gravida, sapien quam mattis elit, id lacinia elit tortor in nisl. Nunc ac purus vitae augue pretium accumsan. Fusce bibendum libero sed quam vestibulum pulvinar. Nam quis dapibus mauris. Nam arcu odio, cursus vitae ipsum et, dictum sagittis nisl. Etiam ornare nibh ut metus sagittis egestas.Donec non turpis nunc. Vivamus dui tortor, consectetur ut mi ut, accumsan suscipit magna. Mauris quis massa sit amet diam mollis efficitur. Phasellus eget leo velit. Mauris semper dignissim fermentum. Fusce a est at risus tincidunt convallis. Nunc vitae tincidunt urna. Praesent quis quam nec orci pharetra rutrum. Curabitur vel mauris imperdiet, molestie urna vel, dapibus sem. Fusce tincidunt vestibulum orci, luctus elementum massa pellentesque a. Donec ullamcorper tortor a nibh accumsan commodo. Sed egestas erat augue, at posuere lacus faucibus non. Vivamus lorem libero, porttitor eget ante non, hendrerit pretium erat. Vestibulum nec venenatis odio. Nullam venenatis metus vitae luctus tincidunt. Fusce et libero eu lacus fermentum egestas.'
    },
    {
        title: 'Esports',
        id: 3,
        image: require('./images/img4.jpg'),
        text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?'
    },
    {
        title: 'New Born',
        id: 4,
        image: require('./images/img5.jpg'),
        text: 'Quisque pharetra ipsum vel urna fermentum fringilla. Quisque et nulla eleifend, porta eros in, faucibus tellus. Maecenas in leo posuere, commodo lectus in, dignissim risus. Duis imperdiet pharetra consequat. Aenean cursus lacinia ipsum, sollicitudin tincidunt lacus facilisis id. Nulla imperdiet massa turpis, sit amet mattis libero maximus vel. Vestibulum eget ligula vel dolor laoreet aliquet vel a tellus. Donec ultricies lacus quis felis egestas placerat. Fusce iaculis id lacus eu pulvinar. Nullam fermentum magna velit, non euismod odio vestibulum vel. Phasellus egestas nisi ut consectetur luctus. Suspendisse sagittis quam in sapien aliquet, quis pellentesque massa ornare. Sed non sagittis nisi, sed fermentum ex. Sed leo justo, pharetra ut pulvinar eget, efficitur a urna Quisque dapibus pretium dui, sit amet congue lacus venenatis non. Aliquam semper dolor sit amet ligula interdum, sed accumsan nunc tempus. Quisque tempor ex lacus, non consectetur tellus pharetra vel. Quisque pretium porta nibh, vel aliquam tortor iaculis ac. Mauris pulvinar nulla eget libero aliquam consequat. Pellentesque eu imperdiet orci. Mauris tincidunt feugiat dapibus. Sed sit amet purus a mi laoreet elementum.',
    }
]

export default data;